/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch Material palette (ported from stitch HTML theme config)
        'surface-bright': '#f6fafe',
        primary: '#005454',
        'on-secondary-fixed-variant': '#614000',
        outline: '#6e7979',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#0d6e6e',
        'on-primary-container': '#9dedec',
        'on-primary': '#ffffff',
        'surface-container-highest': '#dfe3e7',
        'on-surface': '#171c1f',
        'tertiary-fixed': '#d4e4f9',
        background: '#f6fafe',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#d1e1f6',
        'surface-dim': '#d6dade',
        'primary-fixed-dim': '#84d4d3',
        error: '#ba1a1a',
        'secondary-container': '#fdba49',
        'on-primary-fixed': '#002020',
        secondary: '#805600',
        'on-secondary': '#ffffff',
        'inverse-primary': '#84d4d3',
        'surface-container-high': '#e4e9ed',
        'secondary-fixed-dim': '#fdba49',
        'tertiary-container': '#556476',
        'on-surface-variant': '#3e4948',
        'tertiary-fixed-dim': '#b8c8dc',
        'on-tertiary-fixed': '#0d1d2c',
        'on-secondary-container': '#704b00',
        tertiary: '#3d4c5d',
        'inverse-on-surface': '#edf1f5',
        'on-tertiary-fixed-variant': '#394859',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#004f50',
        'inverse-surface': '#2c3134',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#281800',
        surface: '#f6fafe',
        'surface-container-low': '#f0f4f8',
        'outline-variant': '#bec9c8',
        'primary-fixed': '#a0f0f0',
        'error-container': '#ffdad6',
        'on-background': '#171c1f',
        'secondary-fixed': '#ffddaf',
        'surface-tint': '#016a6a',
        'surface-variant': '#dfe3e7',
        'surface-container': '#eaeef2',

        // Custom raw tokens used across sidebar / accent rail
        'nav-dark': '#0F1F2E',
        'nav-dark-elevated': '#172C3F',
        'nav-dark-hover': '#1A2E40',
        'nav-dark-search': '#1A2E3F',
        'gold-accent': '#E8A838',
        'gold-accent-hover': '#D4982E',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Tajawal', 'sans-serif'],
        body: ['"IBM Plex Sans Arabic"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        sans: ['"IBM Plex Sans Arabic"', 'sans-serif'],
      },
      boxShadow: {
        ambient: '0 8px 32px rgba(23, 28, 31, 0.08)',
        'ambient-sm': '0 4px 16px rgba(23, 28, 31, 0.05)',
        'ambient-lg': '0 16px 48px rgba(23, 28, 31, 0.12)',
        'gold-cta': '0 4px 14px rgba(232, 168, 56, 0.35)',
        'primary-cta': '0 4px 14px rgba(13, 110, 110, 0.25)',
      },
      backgroundImage: {
        'primary-gradient': 'linear-gradient(180deg, #005454 0%, #0d6e6e 100%)',
        'gold-gradient': 'linear-gradient(180deg, #E8A838 0%, #D4982E 100%)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
      animation: {
        'fade-in': 'fade-in 200ms ease-out',
        'slide-up': 'slide-up 240ms ease-out',
        'slide-in-right': 'slide-in-right 240ms ease-out',
      },
    },
  },
  plugins: [forms, containerQueries],
};
